// Kenya: 47 counties → sub-counties → key towns.
// Sub-counties are official; towns are the most common urban centers
// per sub-county. This data powers cascading selects for location-based
// matching and shop delivery addresses.
export type KenyaCounty = {
  name: string;
  subCounties: { name: string; towns: string[] }[];
};

export const KENYA: KenyaCounty[] = [
  { name: "Nairobi", subCounties: [
    { name: "Westlands", towns: ["Westlands","Parklands","Highridge","Kangemi","Mountain View"] },
    { name: "Dagoretti North", towns: ["Kilimani","Kawangware","Kileleshwa","Gatina"] },
    { name: "Dagoretti South", towns: ["Ngando","Riruta","Mutuini","Uthiru"] },
    { name: "Lang'ata", towns: ["Lang'ata","Karen","Nairobi West","South C"] },
    { name: "Kibra", towns: ["Kibera","Lindi","Makina","Woodley"] },
    { name: "Roysambu", towns: ["Roysambu","Kahawa West","Zimmerman","Garden Estate"] },
    { name: "Kasarani", towns: ["Kasarani","Mwiki","Clay City","Njiru"] },
    { name: "Ruaraka", towns: ["Babadogo","Korogocho","Lucky Summer","Utalii"] },
    { name: "Embakasi South", towns: ["Pipeline","Imara Daima","Kware","Kwa Njenga"] },
    { name: "Embakasi North", towns: ["Dandora","Kariobangi","Mowlem"] },
    { name: "Embakasi Central", towns: ["Kayole","Komarock","Matopeni","Saika"] },
    { name: "Embakasi East", towns: ["Embakasi","Utawala","Mihango"] },
    { name: "Embakasi West", towns: ["Umoja","Mowlem","Kariobangi South","Maringo"] },
    { name: "Makadara", towns: ["Maringo","Hamza","Viwandani","Harambee"] },
    { name: "Kamukunji", towns: ["Eastleigh","Pumwani","California","Airbase"] },
    { name: "Starehe", towns: ["Nairobi CBD","Pangani","Ngara","Ziwani"] },
    { name: "Mathare", towns: ["Mathare","Huruma","Mlango Kubwa","Hospital"] },
  ]},
  { name: "Mombasa", subCounties: [
    { name: "Mvita", towns: ["Mombasa Island","Old Town","Tudor","Majengo"] },
    { name: "Nyali", towns: ["Nyali","Kongowea","Kadzandani","Frere Town"] },
    { name: "Kisauni", towns: ["Kisauni","Bamburi","Shanzu","Mtopanga"] },
    { name: "Likoni", towns: ["Likoni","Mtongwe","Shika Adabu","Bofu"] },
    { name: "Changamwe", towns: ["Changamwe","Port Reitz","Airport","Miritini"] },
    { name: "Jomvu", towns: ["Jomvu","Mikindani","Magongo"] },
  ]},
  { name: "Kiambu", subCounties: [
    { name: "Thika Town", towns: ["Thika","Makongeni","Witeithie"] },
    { name: "Ruiru", towns: ["Ruiru","Kahawa Sukari","Membley","Kamakis"] },
    { name: "Juja", towns: ["Juja","Witeithie","Gachororo"] },
    { name: "Kiambu Town", towns: ["Kiambu","Riabai","Ndumberi"] },
    { name: "Kikuyu", towns: ["Kikuyu","Kinoo","Zambezi","Sigona"] },
    { name: "Limuru", towns: ["Limuru","Tigoni","Rironi"] },
    { name: "Lari", towns: ["Lari","Kijabe","Kambaa"] },
    { name: "Gatundu North", towns: ["Gatundu","Mang'u"] },
    { name: "Gatundu South", towns: ["Gatundu South","Ndarugu"] },
    { name: "Githunguri", towns: ["Githunguri","Komothai"] },
    { name: "Kabete", towns: ["Wangige","Lower Kabete","Ndenderu"] },
    { name: "Kiambaa", towns: ["Banana","Karuri","Ndenderu"] },
  ]},
  { name: "Nakuru", subCounties: [
    { name: "Nakuru Town East", towns: ["Nakuru CBD","Section 58","Flamingo"] },
    { name: "Nakuru Town West", towns: ["Lanet","London","Kapkures"] },
    { name: "Naivasha", towns: ["Naivasha","Mai Mahiu","Karagita","Kihoto"] },
    { name: "Gilgil", towns: ["Gilgil","Elementaita","Kikopey"] },
    { name: "Molo", towns: ["Molo","Elburgon","Turi"] },
    { name: "Njoro", towns: ["Njoro","Egerton","Mau Narok"] },
    { name: "Rongai", towns: ["Rongai","Salgaa"] },
    { name: "Subukia", towns: ["Subukia","Bahati"] },
    { name: "Bahati", towns: ["Bahati","Dundori"] },
    { name: "Kuresoi North", towns: ["Sirikwa","Olenguruone"] },
    { name: "Kuresoi South", towns: ["Keringet","Kiptagich"] },
  ]},
  { name: "Kisumu", subCounties: [
    { name: "Kisumu Central", towns: ["Kisumu CBD","Milimani","Tom Mboya"] },
    { name: "Kisumu East", towns: ["Kibos","Manyatta","Nyalenda"] },
    { name: "Kisumu West", towns: ["Kombewa","Maseno","Otonglo"] },
    { name: "Seme", towns: ["Bondo","Kombewa","Reru"] },
    { name: "Nyando", towns: ["Awasi","Ahero","Nyando"] },
    { name: "Muhoroni", towns: ["Muhoroni","Chemelil"] },
    { name: "Nyakach", towns: ["Pap Onditi","Katito","Sondu"] },
  ]},
  { name: "Uasin Gishu", subCounties: [
    { name: "Eldoret East", towns: ["Eldoret CBD","Pioneer","Kapsoya"] },
    { name: "Eldoret North", towns: ["Eldoret North","Mois Bridge"] },
    { name: "Eldoret South", towns: ["Eldoret South","Langas"] },
    { name: "Eldoret West", towns: ["Eldoret West","Kapseret"] },
    { name: "Turbo", towns: ["Turbo","Kipkaren"] },
    { name: "Soy", towns: ["Soy","Ziwa"] },
    { name: "Moiben", towns: ["Moiben","Sergoit"] },
    { name: "Ainabkoi", towns: ["Burnt Forest","Kaptagat"] },
    { name: "Kapseret", towns: ["Kapseret","Langas","Cheptiret"] },
    { name: "Kesses", towns: ["Kesses","Lessos"] },
  ]},
  { name: "Machakos", subCounties: [
    { name: "Machakos Town", towns: ["Machakos","Mua","Kola"] },
    { name: "Mavoko", towns: ["Athi River","Mlolongo","Syokimau","Kitengela"] },
    { name: "Kathiani", towns: ["Kathiani","Mitaboni"] },
    { name: "Matungulu", towns: ["Tala","Kangundo Road","Matungulu"] },
    { name: "Kangundo", towns: ["Kangundo","Tala"] },
    { name: "Yatta", towns: ["Matuu","Kithimani"] },
    { name: "Masinga", towns: ["Masinga","Ekalakala"] },
    { name: "Mwala", towns: ["Mwala","Wamunyu"] },
  ]},
  { name: "Kajiado", subCounties: [
    { name: "Kajiado North", towns: ["Ongata Rongai","Kiserian","Ngong"] },
    { name: "Kajiado Central", towns: ["Kajiado","Bissil"] },
    { name: "Kajiado East", towns: ["Kitengela","Isinya","Kipeto"] },
    { name: "Kajiado West", towns: ["Magadi","Ewuaso Kedong"] },
    { name: "Kajiado South", towns: ["Loitokitok","Rombo","Mashuuru"] },
    { name: "Loitokitok", towns: ["Loitokitok","Kimana"] },
  ]},
  { name: "Nyeri", subCounties: [
    { name: "Nyeri Town", towns: ["Nyeri","Ruring'u","Kingongo"] },
    { name: "Tetu", towns: ["Wamagana","Ihururu"] },
    { name: "Kieni East", towns: ["Naromoru","Mweiga"] },
    { name: "Kieni West", towns: ["Mweiga","Bellevue"] },
    { name: "Mathira East", towns: ["Karatina","Kiamabara"] },
    { name: "Mathira West", towns: ["Iriaini","Kihate"] },
    { name: "Mukurweini", towns: ["Mukurweini","Gakindu"] },
    { name: "Othaya", towns: ["Othaya","Mahiga"] },
  ]},
  { name: "Meru", subCounties: [
    { name: "Imenti North", towns: ["Meru Town","Mikinduri","Ruiri"] },
    { name: "Imenti South", towns: ["Nkubu","Chuka Road"] },
    { name: "Imenti Central", towns: ["Kanyakine","Chogoria"] },
    { name: "Buuri", towns: ["Timau","Nanyuki Road"] },
    { name: "Tigania East", towns: ["Muriri","Mikinduri"] },
    { name: "Tigania West", towns: ["Kianjai","Akithi"] },
    { name: "Igembe Central", towns: ["Kangeta","Maua"] },
    { name: "Igembe North", towns: ["Laare","Lailuba"] },
    { name: "Igembe South", towns: ["Maua","Kangeta"] },
  ]},
  { name: "Kakamega", subCounties: [
    { name: "Lurambi", towns: ["Kakamega Town","Mahiakalo"] },
    { name: "Mumias East", towns: ["Mumias","Lubinu"] },
    { name: "Mumias West", towns: ["Mumias West","Etenje"] },
    { name: "Butere", towns: ["Butere","Marenyo"] },
    { name: "Khwisero", towns: ["Khwisero","Kisa"] },
    { name: "Matungu", towns: ["Matungu","Khalaba"] },
    { name: "Navakholo", towns: ["Navakholo","Bunyala"] },
    { name: "Likuyani", towns: ["Likuyani","Sango"] },
    { name: "Lugari", towns: ["Lugari","Lumakanda"] },
    { name: "Malava", towns: ["Malava","Shirugu"] },
    { name: "Shinyalu", towns: ["Shinyalu","Khayega"] },
    { name: "Ikolomani", towns: ["Ikolomani","Idakho"] },
  ]},
  { name: "Bungoma", subCounties: [
    { name: "Bungoma Central", towns: ["Bungoma Town","Sang'alo"] },
    { name: "Bungoma South", towns: ["Webuye","Misikhu"] },
    { name: "Bungoma North", towns: ["Sirisia","Naitiri"] },
    { name: "Bungoma East", towns: ["Chwele","Cheptais"] },
    { name: "Bungoma West", towns: ["Sirisia","Bumula"] },
    { name: "Kimilili", towns: ["Kimilili","Maeni"] },
    { name: "Mt. Elgon", towns: ["Kapsokwony","Kopsiro"] },
    { name: "Tongaren", towns: ["Naitiri","Ndalu"] },
    { name: "Webuye East", towns: ["Webuye","Misikhu"] },
  ]},
  { name: "Kilifi", subCounties: [
    { name: "Kilifi North", towns: ["Kilifi Town","Mnarani"] },
    { name: "Kilifi South", towns: ["Mtwapa","Shimo la Tewa"] },
    { name: "Malindi", towns: ["Malindi","Watamu","Gede"] },
    { name: "Magarini", towns: ["Marafa","Mambrui"] },
    { name: "Ganze", towns: ["Ganze","Bamba"] },
    { name: "Kaloleni", towns: ["Kaloleni","Mariakani"] },
    { name: "Rabai", towns: ["Rabai","Mazeras"] },
  ]},
  { name: "Trans Nzoia", subCounties: [
    { name: "Kiminini", towns: ["Kiminini","Kitale Road"] },
    { name: "Saboti", towns: ["Kitale","Matisi"] },
    { name: "Cherang'any", towns: ["Cherangany","Sinyerere"] },
    { name: "Endebess", towns: ["Endebess","Kapsara"] },
    { name: "Kwanza", towns: ["Kwanza","Bidii"] },
  ]},
  // Remaining counties with their official sub-counties + key towns.
  { name: "Kwale", subCounties: [
    { name: "Matuga", towns: ["Kwale","Tiwi","Diani"] },
    { name: "Msambweni", towns: ["Msambweni","Ukunda","Diani Beach"] },
    { name: "Lunga Lunga", towns: ["Lunga Lunga","Vanga"] },
    { name: "Kinango", towns: ["Kinango","Samburu"] },
  ]},
  { name: "Taita Taveta", subCounties: [
    { name: "Voi", towns: ["Voi","Mwatate Road"] },
    { name: "Mwatate", towns: ["Mwatate","Bura"] },
    { name: "Wundanyi", towns: ["Wundanyi","Werugha"] },
    { name: "Taveta", towns: ["Taveta","Mahoo"] },
  ]},
  { name: "Tana River", subCounties: [
    { name: "Galole", towns: ["Hola","Wenje"] },
    { name: "Garsen", towns: ["Garsen","Witu"] },
    { name: "Bura", towns: ["Bura","Madogo"] },
  ]},
  { name: "Lamu", subCounties: [
    { name: "Lamu East", towns: ["Faza","Kiunga"] },
    { name: "Lamu West", towns: ["Mokowe","Mpeketoni","Hindi"] },
  ]},
  { name: "Garissa", subCounties: [
    { name: "Garissa Township", towns: ["Garissa","Bula Iftin"] },
    { name: "Balambala", towns: ["Balambala","Saka"] },
    { name: "Lagdera", towns: ["Modogashe","Benane"] },
    { name: "Dadaab", towns: ["Dadaab","Liboi"] },
    { name: "Fafi", towns: ["Bura","Hagadera"] },
    { name: "Ijara", towns: ["Masalani","Sangailu"] },
  ]},
  { name: "Wajir", subCounties: [
    { name: "Wajir East", towns: ["Wajir","Khorof Harar"] },
    { name: "Wajir West", towns: ["Griftu","Hadado"] },
    { name: "Wajir North", towns: ["Bute","Gurar"] },
    { name: "Wajir South", towns: ["Habaswein","Diff"] },
    { name: "Eldas", towns: ["Eldas","Lakoley"] },
    { name: "Tarbaj", towns: ["Tarbaj","Sarman"] },
  ]},
  { name: "Mandera", subCounties: [
    { name: "Mandera East", towns: ["Mandera","Bulla Mpya"] },
    { name: "Mandera West", towns: ["Takaba","Lagsure"] },
    { name: "Mandera North", towns: ["Rhamu","Banisa"] },
    { name: "Mandera South", towns: ["Elwak","Shimbir Fatuma"] },
    { name: "Banissa", towns: ["Banissa","Malkamari"] },
    { name: "Lafey", towns: ["Lafey","Fino"] },
  ]},
  { name: "Marsabit", subCounties: [
    { name: "Saku", towns: ["Marsabit","Karare"] },
    { name: "Moyale", towns: ["Moyale","Sololo"] },
    { name: "North Horr", towns: ["North Horr","Maikona"] },
    { name: "Laisamis", towns: ["Laisamis","Loiyangalani"] },
  ]},
  { name: "Isiolo", subCounties: [
    { name: "Isiolo", towns: ["Isiolo","Kambi Garba"] },
    { name: "Garbatulla", towns: ["Garbatulla","Kinna"] },
    { name: "Merti", towns: ["Merti","Sericho"] },
  ]},
  { name: "Tharaka-Nithi", subCounties: [
    { name: "Chuka", towns: ["Chuka","Magumoni"] },
    { name: "Maara", towns: ["Chogoria","Mitheru"] },
    { name: "Tharaka North", towns: ["Marimanti","Gatunga"] },
    { name: "Tharaka South", towns: ["Marimanti","Kathwana"] },
  ]},
  { name: "Embu", subCounties: [
    { name: "Manyatta", towns: ["Embu Town","Runyenjes Road"] },
    { name: "Runyenjes", towns: ["Runyenjes","Kanja"] },
    { name: "Mbeere North", towns: ["Siakago","Kiritiri"] },
    { name: "Mbeere South", towns: ["Kiritiri","Ishiara"] },
  ]},
  { name: "Kitui", subCounties: [
    { name: "Kitui Central", towns: ["Kitui Town","Kalundu"] },
    { name: "Kitui West", towns: ["Matinyani","Kauwi"] },
    { name: "Kitui East", towns: ["Mutito","Endau"] },
    { name: "Kitui South", towns: ["Mutomo","Ikutha","Kanziku"] },
    { name: "Kitui Rural", towns: ["Mulutu","Kwa Vonza"] },
    { name: "Mwingi Central", towns: ["Mwingi","Migwani"] },
    { name: "Mwingi West", towns: ["Migwani","Kyuso"] },
    { name: "Mwingi North", towns: ["Kyuso","Ngomeni"] },
  ]},
  { name: "Makueni", subCounties: [
    { name: "Makueni", towns: ["Wote","Kathonzweni"] },
    { name: "Kibwezi East", towns: ["Mtito Andei","Kambu"] },
    { name: "Kibwezi West", towns: ["Kibwezi","Makindu"] },
    { name: "Kilome", towns: ["Salama","Sultan Hamud"] },
    { name: "Mbooni", towns: ["Tawa","Kikima"] },
    { name: "Kaiti", towns: ["Nunguni","Kilungu"] },
  ]},
  { name: "Nyandarua", subCounties: [
    { name: "Ol Kalou", towns: ["Ol Kalou","Karau"] },
    { name: "Kipipiri", towns: ["Kipipiri","Wanjohi"] },
    { name: "Kinangop", towns: ["Engineer","North Kinangop"] },
    { name: "Ndaragwa", towns: ["Ndaragwa","Shamata"] },
    { name: "Ol Jorok", towns: ["Ol Joro Orok","Charagita"] },
  ]},
  { name: "Kirinyaga", subCounties: [
    { name: "Kirinyaga Central", towns: ["Kerugoya","Kutus"] },
    { name: "Mwea East", towns: ["Wanguru","Kimbimbi"] },
    { name: "Mwea West", towns: ["Mwea","Wamumu"] },
    { name: "Gichugu", towns: ["Kianyaga","Karumandi"] },
    { name: "Ndia", towns: ["Baricho","Kiine"] },
  ]},
  { name: "Murang'a", subCounties: [
    { name: "Kiharu", towns: ["Murang'a","Mbiri"] },
    { name: "Mathioya", towns: ["Kiriaini","Gitugi"] },
    { name: "Kigumo", towns: ["Kangari","Kahuhia"] },
    { name: "Maragwa", towns: ["Maragua","Sabasaba"] },
    { name: "Kandara", towns: ["Kandara","Ngararia"] },
    { name: "Gatanga", towns: ["Gatanga","Thika Road"] },
    { name: "Kangema", towns: ["Kangema","Rwathia"] },
  ]},
  { name: "Baringo", subCounties: [
    { name: "Baringo Central", towns: ["Kabarnet","Kapropita"] },
    { name: "Baringo North", towns: ["Kabartonjo","Bartabwa"] },
    { name: "Baringo South", towns: ["Marigat","Mochongoi"] },
    { name: "Mogotio", towns: ["Mogotio","Emining"] },
    { name: "Eldama Ravine", towns: ["Eldama Ravine","Lembus"] },
    { name: "Tiaty", towns: ["Chemolingot","Kollowa"] },
  ]},
  { name: "Laikipia", subCounties: [
    { name: "Laikipia East", towns: ["Nanyuki","Naro Moru"] },
    { name: "Laikipia West", towns: ["Nyahururu","Rumuruti"] },
    { name: "Laikipia North", towns: ["Doldol","Mukogodo"] },
  ]},
  { name: "Samburu", subCounties: [
    { name: "Samburu East", towns: ["Wamba","Archer's Post"] },
    { name: "Samburu Central", towns: ["Maralal","Suguta Marmar"] },
    { name: "Samburu North", towns: ["Baragoi","South Horr"] },
  ]},
  { name: "Narok", subCounties: [
    { name: "Narok North", towns: ["Narok Town","Ololulunga"] },
    { name: "Narok East", towns: ["Suswa","Olokurto"] },
    { name: "Narok South", towns: ["Ololulunga","Mulot"] },
    { name: "Narok West", towns: ["Lolgorian","Kilgoris"] },
    { name: "Kilgoris", towns: ["Kilgoris","Lolgorian"] },
    { name: "Emurua Dikirr", towns: ["Mogondo","Kapsasian"] },
  ]},
  { name: "Bomet", subCounties: [
    { name: "Bomet Central", towns: ["Bomet","Singorwet"] },
    { name: "Bomet East", towns: ["Longisa","Mulot"] },
    { name: "Sotik", towns: ["Sotik","Ndanai"] },
    { name: "Chepalungu", towns: ["Sigor","Kong'asis"] },
    { name: "Konoin", towns: ["Mogogosiek","Chebunyo"] },
  ]},
  { name: "Kericho", subCounties: [
    { name: "Kericho Town", towns: ["Kericho","Brookside"] },
    { name: "Ainamoi", towns: ["Kapsoit","Sosiot"] },
    { name: "Belgut", towns: ["Sosiot","Cheptororiet"] },
    { name: "Bureti", towns: ["Litein","Roret"] },
    { name: "Kipkelion East", towns: ["Londiani","Kedowa"] },
    { name: "Kipkelion West", towns: ["Kipkelion","Fort Ternan"] },
    { name: "Soin/Sigowet", towns: ["Soin","Sigowet"] },
  ]},
  { name: "Vihiga", subCounties: [
    { name: "Vihiga", towns: ["Mbale","Chavakali"] },
    { name: "Sabatia", towns: ["Sabatia","Wodanga"] },
    { name: "Hamisi", towns: ["Hamisi","Shamakhokho"] },
    { name: "Luanda", towns: ["Luanda","Ebusiratsi"] },
    { name: "Emuhaya", towns: ["Emuhaya","Kima"] },
  ]},
  { name: "Busia", subCounties: [
    { name: "Teso North", towns: ["Amagoro","Malaba"] },
    { name: "Teso South", towns: ["Amukura","Adungosi"] },
    { name: "Nambale", towns: ["Nambale","Bukhayo"] },
    { name: "Matayos", towns: ["Matayos","Busibwabo"] },
    { name: "Butula", towns: ["Butula","Bumala"] },
    { name: "Funyula", towns: ["Funyula","Nangina"] },
    { name: "Budalangi", towns: ["Port Victoria","Sio Port"] },
  ]},
  { name: "Siaya", subCounties: [
    { name: "Siaya Town", towns: ["Siaya","Boro"] },
    { name: "Alego Usonga", towns: ["Boro","Ugunja Road"] },
    { name: "Gem", towns: ["Yala","Sigomere"] },
    { name: "Ugenya", towns: ["Ukwala","Sega"] },
    { name: "Ugunja", towns: ["Ugunja","Sigomere"] },
    { name: "Bondo", towns: ["Bondo","Usenge"] },
    { name: "Rarieda", towns: ["Madiany","Aram"] },
  ]},
  { name: "Homa Bay", subCounties: [
    { name: "Homa Bay Town", towns: ["Homa Bay","Asego"] },
    { name: "Rangwe", towns: ["Rangwe","Pala"] },
    { name: "Ndhiwa", towns: ["Ndhiwa","Riana"] },
    { name: "Suba North", towns: ["Mbita","Sindo"] },
    { name: "Suba South", towns: ["Magunga","Gwassi"] },
    { name: "Karachuonyo", towns: ["Kendu Bay","Oyugis Road"] },
    { name: "Kabondo Kasipul", towns: ["Kosele","Sikri"] },
    { name: "Kasipul", towns: ["Oyugis","Rangwe Road"] },
  ]},
  { name: "Migori", subCounties: [
    { name: "Migori Town", towns: ["Migori","Suna"] },
    { name: "Suna East", towns: ["Suna","Wath Onger"] },
    { name: "Suna West", towns: ["Masara","Wasweta"] },
    { name: "Uriri", towns: ["Uriri","Oyani"] },
    { name: "Awendo", towns: ["Awendo","Sare"] },
    { name: "Rongo", towns: ["Rongo","Kamagambo"] },
    { name: "Nyatike", towns: ["Macalder","Muhuru Bay"] },
    { name: "Kuria East", towns: ["Kegonga","Ntimaru"] },
    { name: "Kuria West", towns: ["Kehancha","Isebania"] },
  ]},
  { name: "Kisii", subCounties: [
    { name: "Kisii Central", towns: ["Kisii Town","Daraja Mbili"] },
    { name: "Kitutu Chache North", towns: ["Marani","Ibeno"] },
    { name: "Kitutu Chache South", towns: ["Suneka","Kegati"] },
    { name: "Nyaribari Chache", towns: ["Keumbu","Birongo"] },
    { name: "Nyaribari Masaba", towns: ["Keroka","Gesusu"] },
    { name: "Bobasi", towns: ["Nyamache","Ogembo"] },
    { name: "Bomachoge Borabu", towns: ["Magenche","Kenyenya"] },
    { name: "Bomachoge Chache", towns: ["Ogembo","Sengera"] },
    { name: "South Mugirango", towns: ["Nyamarambe","Tabaka"] },
  ]},
  { name: "Nyamira", subCounties: [
    { name: "Nyamira North", towns: ["Ekerenyo","Magombo"] },
    { name: "Nyamira South", towns: ["Nyamira","Keroka Road"] },
    { name: "Borabu", towns: ["Nyansiongo","Kebirigo"] },
    { name: "Manga", towns: ["Manga","Magombo"] },
    { name: "Masaba North", towns: ["Rigoma","Gachuba"] },
  ]},
  { name: "Nandi", subCounties: [
    { name: "Nandi Hills", towns: ["Nandi Hills","Kapsimotwa"] },
    { name: "Tinderet", towns: ["Songhor","Tinderet"] },
    { name: "Aldai", towns: ["Kapsabet","Kobujoi"] },
    { name: "Chesumei", towns: ["Chemundu","Kosirai"] },
    { name: "Emgwen", towns: ["Kapsabet","Kilibwoni"] },
    { name: "Mosop", towns: ["Kabiyet","Kurgung"] },
  ]},
  { name: "Elgeyo-Marakwet", subCounties: [
    { name: "Keiyo North", towns: ["Iten","Kapsowar Road"] },
    { name: "Keiyo South", towns: ["Kaptarakwa","Chepkorio"] },
    { name: "Marakwet East", towns: ["Kapsowar","Tot"] },
    { name: "Marakwet West", towns: ["Kapcherop","Cheptongei"] },
  ]},
  { name: "West Pokot", subCounties: [
    { name: "Kapenguria", towns: ["Kapenguria","Makutano"] },
    { name: "Sigor", towns: ["Sigor","Marich"] },
    { name: "Kacheliba", towns: ["Kacheliba","Alale"] },
    { name: "Pokot South", towns: ["Chepareria","Lelan"] },
  ]},
  { name: "Turkana", subCounties: [
    { name: "Turkana Central", towns: ["Lodwar","Kalokol"] },
    { name: "Turkana North", towns: ["Lokitaung","Kibish"] },
    { name: "Turkana South", towns: ["Lokichar","Kainuk"] },
    { name: "Turkana East", towns: ["Lokori","Lomelo"] },
    { name: "Turkana West", towns: ["Kakuma","Lokichoggio"] },
    { name: "Loima", towns: ["Lorugum","Turkwel"] },
  ]},
];


export const KENYA_COUNTY_NAMES = KENYA.map(c => c.name);
export function subCountiesOf(county: string) {
  return KENYA.find(c => c.name === county)?.subCounties ?? [];
}
export function townsOf(county: string, subCounty: string) {
  return subCountiesOf(county).find(s => s.name === subCounty)?.towns ?? [];
}

export const CAREERS = [
  "G4S","Wells Fargo","KK Security","Securex","Riley Services","Bidco",
  "Safaricom","Banking","Teacher","Nurse","Doctor","Engineer","Civil Servant",
  "Police / Military","Boda Boda","Matatu Operator","Farmer","Trader / Business",
  "Construction","Driver","Hospitality","Student","Freelancer","Other",
];
